from datetime import datetime

from ai_research_studio.collectors.http_collector import fetch_json
from ai_research_studio.outputs.markdown_writer import write_markdown
from ai_research_studio.settings import settings


def build_daily_brief_markdown() -> str:
    now = datetime.now()
    payload = fetch_json(settings.test_api_url, timeout=settings.request_timeout)

    origin = payload.get("origin", "unknown")
    url = payload.get("url", settings.test_api_url)
    headers = payload.get("headers", {})

    markdown = f"""# Daily Brief

- Generated at: {now.strftime("%Y-%m-%d %H:%M:%S")}
- Project: {settings.project_name}
- Source URL: {url}
- Origin IP: {origin}

## Summary

This is the first MVP report generated by the local Python pipeline.

## Response Snapshot

- User-Agent: {headers.get("User-Agent", "N/A")}
- Accept: {headers.get("Accept", "N/A")}

## Next Step

- Replace the test endpoint with real research data sources
- Add LLM summarization
- Add scheduled automation
"""
    return markdown


def run_daily_brief() -> str:
    now = datetime.now()
    file_name = f"{now.strftime('%Y-%m-%d')}_daily_brief.md"
    output_path = settings.daily_reports_dir / file_name

    markdown = build_daily_brief_markdown()
    saved_path = write_markdown(output_path, markdown)
    return str(saved_path)